#!/usr/bin/env bash
set -eu

apt install npm -y
python3 -m venv python-discord-insult-bot-venv
if [ -d python-discord-insult-bot-venv/bin ]; then
	source python-discord-insult-bot-venv/bin/activate
fi
cd "$(dirname "$0")"

pip3 install build
pip3 install wheel
pip3 install -r ../../requirements-dev.txt
./install-shellcheck
./install-shfmt
npm install
